/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/* Generated By CANNBot */

/*!
 * \file sinh_struct.h
 * \brief Sinh TilingData and TilingKey definitions (atvoss Elewise mode)
 */

#ifndef SINH_STRUCT_H
#define SINH_STRUCT_H

#include "atvoss/elewise/elewise_base_struct.h"
#include "ascendc/host_api/tiling/template_argument.h"

// TilingData: Elewise mode requires a wrapper struct (cannot use 'using' alias)
struct SinhTilingData {
    ::Ops::Base::EleBaseTilingData baseTiling;
};

// TilingKey: Elewise mode standard declaration
ASCENDC_TPL_ARGS_DECL(Sinh,
    ASCENDC_TPL_UINT_DECL(schMode, 1,
        ASCENDC_TPL_UI_LIST, 0, 1));
ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(
    ASCENDC_TPL_UINT_SEL(schMode,
        ASCENDC_TPL_UI_LIST, 0, 1)));

#endif  // SINH_STRUCT_H
