/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/* Generated By CANNBot */

/*!
 * \file sinh_apt.cpp
 * \brief Sinh Kernel entry point (atvoss Elewise mode)
 */

#include "kernel_operator.h"
#include "arch35/sinh_dag.h"
#include "arch35/sinh_struct.h"
#include "atvoss/elewise/elewise_sch.h"

using namespace Ops::Base;

template <uint64_t schMode>
__global__ __aicore__ void sinh(GM_ADDR x, GM_ADDR y,
                                GM_ADDR workspace, GM_ADDR tiling)
{
    KERNEL_TASK_TYPE_DEFAULT(KERNEL_TYPE_AIV_ONLY);
    REGISTER_TILING_DEFAULT(SinhTilingData);
    GET_TILING_DATA(tilingData, tiling);
    TPipe pipe;

    constexpr bool isNeedCast = std::is_same<DTYPE_X, half>::value ||
                                std::is_same<DTYPE_X, bfloat16_t>::value;

    if constexpr (isNeedCast) {
        using OpDag = NsSinh::SinhWithCast<DTYPE_X>::OpDag;
        ElementwiseSch<schMode, OpDag> sch(&(tilingData.baseTiling), &pipe);
        sch.Init(x, y);
        sch.Process();
    } else {
        using OpDag = NsSinh::SinhWithoutCast<DTYPE_X>::OpDag;
        ElementwiseSch<schMode, OpDag> sch(&(tilingData.baseTiling), &pipe);
        sch.Init(x, y);
        sch.Process();
    }
}
